[package]
name = "rust_engine_3d"
version = "0.1.0"
authors = ["ubuntunux <ubuntunux@gmail.com>"]
edition = "2018"

[dependencies]
ash = "0.31.0"
ash-window = "0.5.0"
bincode = "1.2.1"
byteorder = "1.3.4"
cgmath = "0.17"
chrono = "0.4.15"
env_logger = "0.7.1"
image = "0.23.9"
log = "0.4"
nalgebra = {version = "0.23.1", features = ["serde-serialize"]}
nalgebra-glm = "0.9"
time = "0.1.38"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
winit = "0.24"
winit_input_helper = "0.9.0"
which = "4.0.2"
xml-rs = "0.8"
raw-window-handle = ""
#tobj = "2.0"