[package]
name = "rust_engine_3d"
version = "0.1.0"
authors = ["ubuntunux <ubuntunux@gmail.com>"]
edition = "2018"

[dependencies]
ash = "0.31.0"
ash-window = "0.5.0"
cgmath = "0.17"
chrono = "0.4.15"
env_logger = "0.7.1"
image = "0.10.4"
log = "0.4"
nalgebra = "0.22"
time = "0.1.38"
rand = "0.7"
winit = "0.22"