[package]
name = "rust_engine_3d"
version = "0.1.0"
authors = ["ubuntunux <ubuntunux@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.7.1"
vulkano = "0.19.0"
vulkano-shaders = "0.19.0"
vulkano-win = "0.19.0"
winit = "0.22"
cgmath = "0.17"
png = "0.15.0"
time = "0.1.38"
chrono = "0.4.15"
rand = "0.7"
nalgebra = "0.22"